title: Open Budget Sac
project_type: website
project_status: active
description: Fiscal transparency and visualization web app for the City of Sacramento
comments: This is a great project for new members to get used to working one issues and tasks. It is one of the more approachable projects.
communications: Slack
channels: #proj-openbudgetsac
image_url: screenshot.jpg
project_partner: Dan Fey
project_lead: Brianda Hernandez
technical_lead: Nate Bass
lead_designer: Help Needed
tags: html,css,javascript,react,github,d3js
contributing:
  designer:
    difficulty: easy
    technologies: Figma
    ways_to_contribute: improve existing designs, design new pages
  developer:
    difficulty: easy
    frontend: html,css,javascript,react
    backend: n/a
    technologies: To be announced
    version_control: Github
    repo: /openbudgetsac
    ways_to_contribute: Bug fixing, testing, maintenance; see issues on github
  project_manager:
    difficulty: easy
    technologies: github, slack
    ways_to_contribute: organize and create issues & milestones, work with team members to stay and track and remove roadblocks
roadmap:
  maintenance:
    time_range: Jan 1, 2023 - Jan 1, 2043
  update_data_2024:
    time_range: August 1, 2024 - November 1, 2024
  update_data_2025:
    time_range: August 1, 2025 - November 1, 2025
  update_data_2026:
    time_range: August 1, 2026 - November 1, 2026
  objective: Provide a resource for residents of Sacramento to explore the city budget
  comments:
  outcome: Residents are better informed about where their taxpayer dollars are going
resources:
  documentation:
  tutorials:
  meeting_times: Scheduled for Wednesdays at 6:30 PM and listed on Meetup.
  office_hours: Saturdays at 3:00 PM (Posted on Slack)
screenshots:
  - screenshot.jpg
