# This workflow will do a clean install of node dependencies, build the source code, and run unit tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test on staging

on:
  pull_request:
    branches: [staging]
  push:
    branches: [staging]

jobs:
  build:
    runs-on: macos-10.15

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Webpack
        run: cd _src && rm -rf node_modules && npm install && npm run build --if-present
        env:
          CI: true
      - name: Build
        run: bash _src/_compile.sh
        env:
          CI: true
